print("A Shinigami [verb] my [adjective] [noun] out of the [noun] as if he were a vegetarian fishing a [noun] out of his salad.")
verb = input("Enter a verb:")
adjective = input("Enter an adjective:")
noun_1 = input("Enter a noun:")
noun_2 = input("Enter a noun:")
noun_3 = input("Enter a noun:")
print(f"A Shinigami {verb} my {adjective} {noun_1} out of the {noun_2} as if he were a vegetarian fishing a {noun_3} out of his salad.")